git:
  pagers:
    - colorArg: always
      pager: delta-auto --paging=never
  # Command used when displaying the current branch git log in the main window
  branchLogCmd: git lg --color=always {{branchName}} --
  # Commands used to display git log of all branches in the main window, they will be cycled in order of appearance (array of strings)
  allBranchesLogCmds:
    - git lg --color=always --all
  # If true, periodically fetch from remote
  autoFetch: false
  # If true, pass the --all arg to git fetch
  fetchAll: false
  externalDiffCommand: "code --wait --diff"
  commitPrefix:
    - pattern: "^(PM-\\d+|MOIA-\\d+|NOTICKET).*"
      replace: "$1: "
gui:
  theme:
    selectedLineBgColor:
      - default # reverse
  # Nerd fonts version to use.
  # One of: '2' | '3' | empty string (default)
  # If empty, do not show icons.
  nerdFontsVersion: "3"
  # If true (default), file icons are shown in the file views. Only relevant if NerdFontsVersion is not empty.
  showFileIcons: true
  # If true, increase the height of the focused side window; creating an accordion effect.
  expandFocusedSidePanel: true
  enlargedSideViewLocation: left
customCommands:
  - key: <c-f>
    description: Fetch branch
    context: localBranches
    command: git fetch origin {{.SelectedLocalBranch.Name}}
  - key: <c-r>
    description: Rebase
    context: localBranches
    command: git pull --rebase origin {{.SelectedLocalBranch.Name}}
os:
  # A shell startup file containing shell aliases or shell functions. This will be
  # sourced before running any shell commands, so that shell functions are
  # available in the `:` command prompt or even in custom commands.
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#using-aliases-or-functions-in-shell-commands
  shellFunctionsFile: ~/.shell-functions
  editPreset: "vscode"

  # clip being an exectuable script, executing netcat to clipper
  # copyToClipboardCmd: 'printf {{text}} | clip'
